# Generated by Django 3.2.5 on 2021-08-01 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app_daily_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_column='date', max_length=20, null=True)),
                ('shift', models.CharField(db_column='shift', max_length=20, null=True)),
                ('max_value_breached', models.IntegerField(db_column='max_value_breached', null=True)),
                ('min_value_breached', models.IntegerField(db_column='min_value_breached', null=True)),
                ('kks_inactive_count', models.IntegerField(db_column='kks_inactive_count', null=True)),
                ('kks_reading_percentage', models.FloatField(db_column='kks_reading_percentage', max_length=200, null=True)),
            ],
            options={
                'db_table': 'app_daily_stats',
            },
        ),
        migrations.CreateModel(
            name='kks_description',
            fields=[
                ('kks', models.CharField(db_column='kks', max_length=50, primary_key=True, serialize=False)),
                ('category', models.CharField(db_column='category', max_length=50, null=True)),
                ('location', models.CharField(db_column='location', max_length=50, null=True)),
                ('area', models.CharField(db_column='area', max_length=200, null=True)),
                ('description', models.CharField(db_column='description', max_length=200, null=True)),
                ('process_parameter', models.CharField(db_column='process_parameter', max_length=200, null=True)),
                ('unit', models.CharField(db_column='unit', max_length=200, null=True)),
                ('local_only', models.CharField(db_column='local_only', max_length=200, null=True)),
                ('daily_reading', models.CharField(db_column='daily_reading', max_length=200, null=True)),
                ('standby_readings', models.CharField(db_column='standby_readings', max_length=200, null=True)),
                ('min_value', models.FloatField(db_column='min_value', null=True)),
                ('max_value', models.FloatField(db_column='max_value', null=True)),
            ],
            options={
                'db_table': 'kks_description',
            },
        ),
        migrations.CreateModel(
            name='data_input_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_column='date', max_length=50)),
                ('value', models.FloatField(db_column='value', null=True)),
                ('inactive', models.CharField(db_column='inactive', max_length=10, null=True)),
                ('remarks', models.CharField(db_column='remarks', max_length=200, null=True)),
                ('kks_code', models.ForeignKey(blank=True, db_column='kks_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kks_code', to='dataLogging.kks_description')),
            ],
            options={
                'db_table': 'data_input_table',
                'unique_together': {('kks_code', 'date')},
            },
        ),
    ]
